name: 'Terraform Azure DESTROY'
 
on: workflow_dispatch
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_tf_state_rsg: ${{ secrets.TF_STATE_RSG }}
      TF_VAR_tf_state_sta: ${{ secrets.TF_STATE_STA }}
      TF_VAR_openDoor: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "./"

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.0.2

    - name: 'Terraform Init'
      id: init
      run: | 
        terraform init \
          -backend-config=resource_group_name=${TF_VAR_tf_state_rsg} \
          -backend-config=storage_account_name=${TF_VAR_tf_state_sta}

    - name: 'Terraform Destroy'
      id: destroy
      run: terraform destroy -auto-approve -var-file=variables.tfvars
